#' Save a ggplot2 plot to file and update file EXIF metadata
#'
#' @description
#' Save a plot or map then update the EXIF metadata for the title, author, and
#' create data. [ggsave_ext()] also supports creating a file name based on a
#' sentence case name with spaces (e.g. "Baltimore city map") and appending a
#' label (e.g. "baltcity") as a prefix to the output file name.
#'
#' [map_ggsave_ext()] can take a list of {ggplot2} plots (e.g. a list of plot
#' generated by [purrr::map()]) and create multiple files using the same
#' parameters or use the {gridExtras} package to create a single combined PDF
#' file.
#'
#' @param plot Plot to save, defaults to last plot displayed. If plot is an
#'   "magick-image" class object, it is converted to a plot using
#'   [magick::image_ggplot()]
#' @inheritParams ggplot2::ggsave
#' @param name Plot name, used to create filename (if filename is `NULL`) using
#'   [filenamr::make_filename()]
#' @inheritParams filenamr::make_filename
#' @param paper Paper matching name from `paper_sizes` (e.g. "letter"). Not case
#'   sensitive.
#' @param orientation Page orientation ("portrait", "landscape", or "square").
#' @param asp Numeric aspect ratio used to determine width or height if only one
#'   of the two arguments is provided; defaults to `NULL`.
#' @param bgcolor Background color to optionally override `plot.background`
#'   theme element.
#' @param exif If `TRUE`, the EXIF metadata for the exported file is updated
#'   with the exifr package; defaults to `FALSE`.
#' @param overwrite If `TRUE` (default), overwrite any existing file with the
#'   same name or ask to overwrite if `ask = TRUE`. Passed to
#'   [filenamr::check_file_overwrite()].
#' @param ask If `TRUE`, ask before overwriting file with the same name.
#'   Defaults to `FALSE`. Passed to [filenamr::check_file_overwrite()].
#' @inheritParams filenamr::write_exif
#' @param preview If `TRUE`, open saved file in default system application.
#'   Based on [ggpreview()] from tjmisc package.
#' @inheritDotParams ggplot2::ggsave -width -height -units -bg
#' @seealso
#'  [ggplot2::ggsave()]
#' @rdname ggsave_ext
#' @export
#' @importFrom cli cli_alert_success
ggsave_ext <- function(plot = ggplot2::last_plot(),
                       name = NULL,
                       label = NULL,
                       prefix = NULL,
                       postfix = NULL,
                       filename = NULL,
                       device = NULL,
                       fileext = NULL,
                       filetype = NULL,
                       path = NULL,
                       paper = NULL,
                       orientation = NULL,
                       width = NULL,
                       height = NULL,
                       asp = NULL,
                       units = getOption("papersize.ggsave_units", "in"),
                       scale = 1,
                       dpi = 300,
                       bgcolor = NULL,
                       exif = FALSE,
                       title = NULL,
                       author = NULL,
                       keywords = NULL,
                       args = NULL,
                       overwrite = TRUE,
                       ask = FALSE,
                       preview = FALSE,
                       limitsize = TRUE,
                       quiet = FALSE,
                       ...) {
  check_installed("filenamr")

  fileext <- fileext %||% filetype
  params <- rlang::list2(...)

  cli_quiet(quiet)

  dims <-
    set_ggsave_dims(
      paper = paper,
      orientation = orientation,
      width = width,
      height = height,
      asp = asp,
      units = units,
      limitsize = limitsize
    )

  if (!is_null(fileext) | !is_null(filename)) {
    fileext <- fileext %||% str_extract_fileext(filename)

    if (!is_null(filename)) {
      filename <- str_remove_fileext(filename, fileext)
    }
  }

  if ((fileext == "pdf") & isTRUE(capabilities()[["cairo"]])) {
    device <- device %||% grDevices::cairo_pdf
    if (!is_patchwork(plot)) {
      params$symbolfamily <- params$symbolfamily %||% plot[["theme"]][["text"]][["family"]]
    } else {
      params$symbolfamily <- params$symbolfamily %||% plot$theme$text$family
    }
  }

  check_installed("janitor")

  filename <-
    filenamr::make_filename(
      name = name,
      label = label,
      filename = filename,
      fileext = fileext,
      path = path,
      prefix = prefix,
      postfix = postfix
    )

  filenamr::check_file_overwrite(
    filename = filename,
    overwrite = overwrite,
    ask = ask
  )

  if (inherits(plot, "magick-image")) {
    check_installed("magick")
    cli::cli_alert_success(
      "Converting {.arg plot} from {.cls magick-image} to {.cls ggplot}."
    )
    plot <- magick::image_ggplot(plot)
  }

  check_ggplot(plot, class = "arrangelist")

  rlang::exec(
    ggplot2::ggsave,
    filename = filename,
    plot = plot,
    device = device,
    scale = scale,
    width = dims$width,
    height = dims$height,
    units = dims$units,
    dpi = dpi,
    bg = bgcolor,
    !!!params
  )

  cli::cli_alert_success(
    c("v" = "Saving {.path {filename}}.")
  )

  if (exif) {
    filenamr::write_exif(
      path = filename,
      fileext = fileext,
      title = title,
      author = author,
      keywords = keywords,
      date = NULL,
      args = args
    )
  }

  if (preview) {
    system2("open", filename)
  }

  invisible(plot)
}

#' Units that work wth ggsave
#'
#' @noRd
gg_units <-
  list(
    "in" = c("inch", "inches"),
    "cm" = c("centimeter", "centimetre", "centimeters", "centimetres"),
    "mm" = c("millimeter", "millimetre", "millimeters", "millimetres"),
    "px" = c("pixel", "pixels")
  )

#' Set the dimensions of a plot for ggsave_ext()
#'
#' @noRd
#' @importFrom cli cli_alert_warning
set_ggsave_dims <- function(paper = NULL,
                            orientation = NULL,
                            width = NULL,
                            height = NULL,
                            asp = NULL,
                            units = getOption("papersize.ggsave_units", "in"),
                            limitsize = TRUE,
                            cols = c("width", "height")) {
  units_col <- get_units_col()
  if (!is_null(paper)) {
    paper <- get_page_size(paper, orientation = orientation)

    dims <-
      list(
        "width" = paper[[cols[1]]],
        "height" = paper[[cols[2]]],
        "units" = paper[[units_col]]
      )

    return(dims)
  }

  page <-
    make_page_size(
      width = width,
      height = height,
      asp = asp,
      units = units,
      valid_units = names(gg_units)
    )

  page[[units_col]] <-
    replace_with_gg_units(
      page[[units_col]]
    )

  dims <-
    list(
      "width" = page[[cols[1]]],
      "height" = page[[cols[2]]],
      "units" = page[[units_col]]
    )

  if (any((c(dims[["width"]], dims[["height"]]) > 50)) && (units == "in") && limitsize) {
    cli::cli_alert_warning(
      "Switching {.arg units} from default {.val in} to {.val px} when
      dimensions exceed 50 inches and {.code limitsize = TRUE}."
    )

    dims$units <- "px"
  }

  dims
}

#' Convert long versions of unit types from grid to ggsave compatible versions
#'
#' @noRd
replace_with_gg_units <- function(x) {
  for (i in seq_along(gg_units)) {
    x[x %in% gg_units[[i]]] <- names(gg_units)[[i]]
  }

  x
}

#' @rdname ggsave_ext
#' @name ggsave_social
#' @param image Image name passed to name parameter of [get_social_size()].
#' @inheritParams get_social_size
#' @export
#' @importFrom rlang exec list2
ggsave_social <- function(plot = ggplot2::last_plot(),
                          image = "Instagram post",
                          platform = NULL,
                          format = NULL,
                          orientation = NULL,
                          name = NULL,
                          filename = NULL,
                          fileext = "jpeg",
                          filetype = NULL,
                          dpi = 72,
                          width = 1080,
                          height = 1080,
                          units = "px",
                          ...) {
  fileext <- fileext %||% filetype

  image_size <-
    get_social_size(
      name = image,
      platform = platform,
      format = format,
      orientation = orientation
    )

  params <-
    modify_fn_fmls(
      params = rlang::list2(...),
      fn = ggsave_ext,
      plot = plot,
      width = image_size$width,
      height = image_size$height,
      name = name,
      filename = filename,
      fileext = fileext,
      units = units
    )

  rlang::exec(
    ggsave_ext,
    !!!params
  )
}

#' @name map_ggsave_ext
#' @rdname ggsave_ext
#' @param single_file If `TRUE`, use [gridExtra::arrangeGrob()] to create an
#'   arrangelist class object that [ggplot2::ggsave()] can save as a single
#'   multi-page file. Note: this does not work with plots modified with
#'   patchwork including inset maps created with the
#'   [maplayer::layer_inset()] function.
#' @export
#' @importFrom cli cli_bullets
map_ggsave_ext <- function(plot,
                           name = NULL,
                           label = NULL,
                           prefix = NULL,
                           postfix = "pg_",
                           filename = NULL,
                           device = NULL,
                           fileext = NULL,
                           filetype = NULL,
                           path = NULL,
                           overwrite = TRUE,
                           ...,
                           single_file = TRUE,
                           onefile = TRUE) {
  fileext <- fileext %||% filetype

  if (!identical(single_file, onefile)) {
    cli::cli_alert_warning(
      "{.arg single_file} and {.arg onefile} do not match."
    )
  }

  # single_file <- onefile

  if (!is_gg_list(plot)) {
    cli_abort(
      c("{.arg plot} must be a list of {.cls gg} objects.",
        "i" = "Use {.fn ggsave_ext} for a single plot."
      )
    )
  }

  check_installed("janitor")

  filename <-
    filenamr::make_filename(
      name = name,
      label = label,
      filename = filename,
      fileext = fileext,
      path = NULL,
      prefix = prefix
    )

  is_patchwork_plot <- is_patchwork(plot) || is_patchwork(plot[[1]])

  if ((single_file | onefile) & !is_patchwork_plot) {
    check_installed("gridExtra")

    plot <-
      map(
        seq(plot),
        function(x) {
          gridExtra::arrangeGrob(plot[[x]])
        }
      )

    class(plot) <- c("arrangelist", class(plot))

    ggsave_ext(
      plot = plot,
      filename = filename,
      path = path,
      device = device,
      ...
    )

    return(invisible(plot))
  }

  if (single_file || onefile) {
    if (has_fileext(filename, "pdf")) {
      output_path <- path %||% getwd()
      input_path <- tempdir()
      path <- input_path
    } else {
      cli::cli_bullets(
        c(
          "!" = "{.arg single_file} = TRUE only works with {.cls patchwork}
          plots when saving a pdf file.",
          "i" = "Setting {.arg single_file} to {.code FALSE}."
        )
      )
      single_file <- FALSE
    }
  }

  for (pg in seq_along(plot)) {
    pg_postfix <- glue("{postfix}{pg}")

    ggsave_ext(
      plot = plot[[pg]],
      postfix = pg_postfix,
      filename = filename,
      path = path,
      device = device,
      ...
    )
  }

  if (!single_file && !onefile) {
    return(invisible(plot))
  }

  check_installed("qpdf")

  filenamr::check_file_overwrite(
    filename = filename,
    path = output_path,
    overwrite = overwrite,
    ask = FALSE
  )

  input <- file.path(input_path, filename)

  qpdf::pdf_combine(
    input = input,
    output = file.path(output_path, filename)
  )

  unlink(input, recursive = TRUE)
}
